# Generated by Django 3.2.7 on 2021-10-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20210930_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tag',
            field=models.ManyToManyField(max_length=1200, to='bookstore.Tag'),
        ),
    ]
